/**
 * @constant 
 * UPDATE_USERINFO              更新登录用户信息
 * UPDATE_TOURISTINFO           更新游客信息
 * UPDATE_GLOBALMASK            更新全局蒙版
 * UPDATE_LYRICSTATE            更新歌词状态
 * UPDATE_USERSETTINGSTATE      更新用户设置状态
 * UPDATE_SYSTEMSETTINGSTATE    更新系统设置状态
 * UPDATE_USERPANELSTATE        更新用户面板状态
 */

export const UPDATE_USERINFO = 'UPDATE_USERINFO';

export const UPDATE_TOURISTINFO = 'UPDATE_TOURISTINFO';

export const UPDATE_GLOBALMASK = 'UPDATE_GLOBALMASK';

export const UPDATE_LYRICSTATE = 'UPDATE_LYRICSTATE';

export const UPDATE_USERSETTINGSTATE = 'UPDATE_USERSETTINGSTATE';

export const UPDATE_SYSTEMSETTINGSTATE = 'UPDATE_SYSTEMSETTINGSTATE';

export const UPDATE_USERPANELSTATE = 'UPDATE_USERPANELSTATE';
