/**
 * @constant 
 * UPDATE_CONNECTSTATE          更新连接状态
 * UPDATE_USERINFO              更新登录用户信息
 * UPDATE_TOURISTINFO           更新游客信息
 * UPDATE_GLOBALMASK            更新全局蒙版
 * UPDATE_LYRICSTATE            更新歌词状态
 * UPDATE_USERSETTINGSTATE      更新用户设置状态
 * UPDATE_SYSTEMSETTINGSTATE    更新系统设置状态
 * UPDATE_USERPANELSTATE        更新用户面板状态
 * UPDATE_ROOMNOTICESTATE       更新聊天室消息窗口状态
 * UPDATE_ROOMINFOSTATE         更新聊天室信息窗口状态
 * UPDATE_EXPRESSIONSTATE       更新表情界面状态
 * UPDATE_CODEINPUTSTATE        更新代码输入窗口状态
 * UPDATE_CONTACTSPANELSTATE    更新联系人面板状态
 */

export const UPDATE_CONNECTSTATE = 'UPDATE_CONNECTSTATE';

export const UPDATE_USERINFO = 'UPDATE_USERINFO';

export const UPDATE_TOURISTINFO = 'UPDATE_TOURISTINFO';

export const UPDATE_GLOBALMASK = 'UPDATE_GLOBALMASK';

export const UPDATE_LYRICSTATE = 'UPDATE_LYRICSTATE';

export const UPDATE_USERSETTINGSTATE = 'UPDATE_USERSETTINGSTATE';

export const UPDATE_SYSTEMSETTINGSTATE = 'UPDATE_SYSTEMSETTINGSTATE';

export const UPDATE_USERPANELSTATE = 'UPDATE_USERPANELSTATE';

export const UPDATE_ROOMNOTICESTATE = 'UPDATE_ROOMNOTICESTATE';

export const UPDATE_ROOMINFOSTATE = 'UPDATE_ROOMINFOSTATE';

export const UPDATE_EXPRESSIONSTATE = 'UPDATE_EXPRESSIONSTATE';

export const UPDATE_CODEINPUTSTATE = 'UPDATE_CODEINPUTSTATE';

export const UPDATE_CONTACTSPANELSTATE = 'UPDATE_CONTACTSPANELSTATE';