/**
 * @constant 
 * UPDATE_CONNECTSTATE          更新连接状态
 * UPDATE_USERINFO              更新登录用户信息
 * UPDATE_TOURISTINFO           更新游客信息
 * UPDATE_GLOBALMASK            更新全局蒙版
 * UPDATE_LYRICSTATE            更新歌词状态
 * UPDATE_USERSETTINGSTATE      更新用户设置状态
 * UPDATE_SYSTEMSETTINGSTATE    更新系统设置状态
 * UPDATE_USERPANELSTATE        更新用户面板状态
 * UPDATE_ROOMNOTICESTATE       更新聊天室消息窗口状态
 * UPDATE_ROOMINFOSTATE         更新聊天室信息窗口状态
 * UPDATE_EXPRESSIONSTATE       更新表情界面状态
 * UPDATE_CODEINPUTSTATE        更新代码输入窗口状态
 * UPDATE_CONTACTSPANELSTATE    更新联系人面板状态
 * DELETE_DB_MESSAGE            删除数据库消息    
 * 
 * UPDATE_ONLINEUSERS           更新在线用户数   
 * UPDATE_MYUSERLISTARR         更新我的当前聊天用户列表     
 * UPDATE_CURRENTCHATDATA       更新当前聊天面板数据  
 * UPDATE_USERLIST              更新用户列表
 * UPDATE_CURRENTCHATUSERINFO   更新当前聊天用户信息
 * UPDATE_LOADING               更新数据加载状态
 * CLEAR_HISTORY                清空用户历史数据
 * 
 * UPDATE_LATEST_MESSAGE        更新收到的最新消息
 * UPDATE_TYPINGSTATE           更新打字状态
 * UPDATE_SEARCHUSERRES         查询用户结果
 * UPDATE_MYCONTACTSLIST        更新我的联系人列表
 */

export const UPDATE_CONNECTSTATE = 'UPDATE_CONNECTSTATE';

export const UPDATE_USERINFO = 'UPDATE_USERINFO';

export const UPDATE_TOURISTINFO = 'UPDATE_TOURISTINFO';

export const UPDATE_GLOBALMASK = 'UPDATE_GLOBALMASK';

export const UPDATE_LYRICSTATE = 'UPDATE_LYRICSTATE';

export const UPDATE_USERSETTINGSTATE = 'UPDATE_USERSETTINGSTATE';

export const UPDATE_SYSTEMSETTINGSTATE = 'UPDATE_SYSTEMSETTINGSTATE';

export const UPDATE_USERPANELSTATE = 'UPDATE_USERPANELSTATE';

export const UPDATE_ROOMNOTICESTATE = 'UPDATE_ROOMNOTICESTATE';

export const UPDATE_ROOMINFOSTATE = 'UPDATE_ROOMINFOSTATE';

export const UPDATE_EXPRESSIONSTATE = 'UPDATE_EXPRESSIONSTATE';

export const UPDATE_CODEINPUTSTATE = 'UPDATE_CODEINPUTSTATE';

export const UPDATE_CONTACTSPANELSTATE = 'UPDATE_CONTACTSPANELSTATE';

export const DELETE_DB_MESSAGE = 'DELETE_DB_MESSAGE';


// Chat

export const UPDATE_ONLINEUSERS = 'UPDATE_ONLINEUSERS';

export const UPDATE_MYUSERLISTARR = 'UPDATE_MYUSERLISTARR';

export const UPDATE_CURRENTCHATDATA = 'UPDATE_CURRENTCHATDATA';

export const UPDATE_USERLIST = 'UPDATE_USERLIST';

export const UPDATE_CURRENTCHATUSERINFO = 'UPDATE_CURRENTCHATUSERINFO';

export const UPDATE_LOADING = 'UPDATE_LOADING';

export const CLEAR_HISTORY = 'CLEAR_HISTORY';


export const UPDATE_LATEST_MESSAGE = 'UPDATE_LATEST_MESSAGE';

export const UPDATE_TYPINGSTATE = 'UPDATE_TYPINGSTATE';

export const UPDATE_SEARCHUSERRES = 'UPDATE_SEARCHUSERRES';

export const UPDATE_MYCONTACTSLIST = 'UPDATE_MYCONTACTSLIST';